dailyLog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('show_diary/', showDiary_views, name='showDia'),
    path('newEdit_diary/', newEditDiary_views, name='newEditDia'),
    path('show_inspiration/', showInspiration_views, name='showIns'),
    path('newEdit_inspiration/', newEditInspiration_views, name='newEditIns')
]

learning_log/urls.py
# 当前的URL文件位于下面注释中的文件中
"""定义learning_logs的URL模式"""
# 导入函数url将URL映射到试图
from django.conf.urls import url
from django.urls import path
# 导入views模块，其中的句点是让python从当前文件夹中导入视图
from . import views

# 包含可在应用程序learning_logs中请求的网页
urlpatterns = [
    # 主页
    # 添加代码来包含模块learning_logs，namespace是为了让learning_log的URL中的其他URL区分开来
    # 函数接收3个实参，第一个是正则表达式，找开头和结尾之间没有任何东西的URL，
    # 第二个实参指定了要调用的视图函数
    # 第三个实参将这个URL模式的名称指定为index，依此让我们在代码的其他地方引用它
    path('', views.index, name='index'),
    # 显示所有的主题
    path('topics/', views.topics, name='topics'),
    path('topic/(<topic_id>)/', views.topic, name='topic'),  # 与包含在两个斜杠内的整数匹配，#将捕获的值存储到topic_id中
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/(<topic_id>)/', views.new_entry, name='new_entry'),
    path('edit_entry/(<entry_id>)/', views.edit_entry, name='edit_entry'),
]
app_name = 'learning_log'

learning_logs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('', include(('learning_log.urls', 'learning_log'), namespace="learning_log")),
    path('dailyLog/', include(('dailyLog.urls', 'dailyLog'), namespace='dailyLog')),
    path('titles/', include(('titles.urls', 'title'), namespace='title')),
    path('comments/', include(('comments.urls', 'comment'), namespace='comment')),
]

ll_env/Scripts/learning_logs/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

titles/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('show_titles/', index, name='titles'),
    path('post/<int:pk>/', detail, name='detail'),
    path('archives/<int:year>/<int:month>/', archive, name='archive'),
    path('categories/<int:pk>/', category, name='category'),
    path('tags/<int:pk>/', tag, name='tag'),
]

user/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import *

urlpatterns = [
    # path('showUser/', showUser_views),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),
]

learning_log/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200,verbose_name='科目')  # 由字符或文本组成的数据，需要存储少量的文本 定义CharFiled属性时需要告诉Django在该数据库预留多少空间，即max_length=200
    date_added = models.DateTimeField(auto_now_add=True)  # 记录日期和时间的数据，auto_now_add=True是让Django将这个属性自动设置成当前日期和时间
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='拥有者',default=1)

    class Meta:
        verbose_name = '科目'
        verbose_name_plural = verbose_name
        ordering = ['date_added']

    def __str__(self):  # 告诉Django默认使用那个属性来显示有关主题的信息，即__str__这个属性
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='知识点')  # 将每个条目关联到特定的主题,设置Entry为Topic外键
    text = models.TextField(verbose_name='笔记')  # 不限制文本长度
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '笔记'
        verbose_name_plural = verbose_name
        ordering = ['date_added']

    def __str__(self):  # 用此方法来告诉Django只显示text的前50个字符
        return self.text[:50] + '...'

learning_log/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    """继承自froms的ModelForm"""

    class Meta:
        # 内嵌的类告诉FDjango根据哪个模型创建表单，以及在表单中包含哪些字段
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/views.py
from django.shortcuts import render
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_log/index.html')


@login_required
def topics(request):
    """显示所有的主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_log/topics.html', context)


@login_required
def topic(request, topic_id):  # 接收正则表达式捕获的值并存储到topic_id中
    """显示单个主题及所有的条目"""
    topic = Topic.objects.get(id=topic_id)  # 使用get()来获取指定的主题
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')  # 获取与该主题相关联的条目并将它们按date_added排序，前面的-号指按降序排列
    context = {'topic': topic, 'entries': entries}  # 将主题和条目都存储在字典中，再将这个字典发送给模板topic.html
    return render(request, 'learning_log/topic.html', context)


@login_required
def new_topic(request):
    """添加新主题"""
    # 从服务器读取数据的页面使用GET请求，用户需要通过表单提交信息时，使用POS请求
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():  # 如果信息是有效的，保存到数据库
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(
                reverse(
                    'learning_log:topics'))  # 用reverse获取页面topics的URL，将其传递给HttpResponseRedirect(),后者将用户的浏览器重定向到页面Topics
    context = {'form': form}  # 通过上下文将这个表单发送给模板
    return render(request, 'learning_log/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_log:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_log/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_log:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_log/edit_entry.html', context)

learning_log/templates/learning_log/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning log</title>
    <link rel="stylesheet" href="/static/css/2.css/">
</head>
<body>
<div align="center" id="base_view">
    <div><a href="{% url 'learning_log:index' %}" class="a_index">Return</a></div>
    <div><a href="{% url 'learning_log:topics' %}" class="a_index">Learning Log</a></div>
    <div><a href="{% url 'dailyLog:showDia' %}" class="a_index">Diary</a></div>
    <div><a href="{% url 'dailyLog:showIns' %}" class="a_index">Inspiration</a></div>
    <div><a href="{% url 'title:titles' %}" class="a_index">Blog</a></div>
    {% if user.is_authenticated %}
    <div style="color: white; float: right;">{{user.username}}</div>
    <div><a href="{% url 'user:logout' %}" class="c_index">Log Out</a></div>
    {% else %}
    <div><a href="{% url 'user:register' %}" class="b_index">Register</a></div>
    <div><a href="{% url 'user:login' %}" class="b_index">Log in</a></div>
    {% endif %}
</div>
<div>
    <img src="/static/img/123.png/" width="100%">
</div>
{% block content %}
{% endblock content %}<!--块标签，占位符-->
</body>
</html>

learning_log/templates/learning_log/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit_entry</title>
</head>
<body>
    {% extends "learning_log/base.html" %}<!--第一行必须包含此标签，让Django知道它继承哪个夫模板-->
    {% block content %}
    <p>
        <a href="{% url 'learning_log:topic' topic.id %}">{{topic}}</a>
    </p>
    <p>Edit entry:</p>
<!--    action是向何处发送表单数据，post是向服务器提交数据-->
    <form action="{% url 'learning_log:edit_entry' entry.id %}" method='post'>
        {% csrf_token%}
        {{form.as_p}}
        <button name="submit">submit</button>
    </form>
    {% endblock content %}
</body>
</html>

learning_log/templates/learning_log/index.html
<!--继承模板-->
<!--在子模块中只需包含当前网页特有的内容-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人主页</title>
    <link rel="stylesheet" href="/static/css/style.css/">
</head>
<body>
    {% extends "learning_log/base.html" %}<!--第一行必须包含此标签，让Django知道它继承哪个夫模板-->
    {% block content %}
<!--    <div id="index_view" align="center">-->
<!--        <img src="/static/img/love.jpg/" id="index_img1">-->
<!--    </div>-->
    {% endblock content %}
</body>
</html>

learning_log/templates/learning_log/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new_entry</title>
</head>
<body>
{% extends "learning_log/base.html" %}<!--第一行必须包含此标签，让Django知道它继承哪个夫模板-->
{% block content %}
<p>
    <a href="{%url 'learning_log:topic' topic.id%}">{{topic}}</a>
</p>
<form action="{%url 'learning_log:new_entry' topic.id%}" method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name='submit'>Add</button>
</form>
{% endblock content %}
</body>
</html>

learning_log/templates/learning_log/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
{% extends "learning_log/base.html" %}<!--第一行必须包含此标签，让Django知道它继承哪个夫模板-->
{% block content %}
<form action="{%url 'learning_log:new_topic'%}" method="post">
    {% csrf_token %}<!--防止攻击者利用表单来获得对服务器未经授权的访问-->
    {{ form.as_p }}<!--显示表单，修饰符as_p让Django一段落格式渲染所有表单元素-->
    <button name="submit">Add</button>
</form>
{% endblock content %}
</body>
</html>

learning_log/templates/learning_log/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>指定主题</title>
    <link rel="stylesheet" href="style.css">

</head>
<body>
{% extends 'learning_log/base.html' %}<!--第一行必须包含此标签，让Django知道它继承哪个夫模板-->
{% block content %}
<p>Topic:{{topic}}</p>

<p>Notes:</p>
<p>
    <a href="{%url 'learning_log:new_entry' topic.id%}">Add</a>
</p>
<ul>
    {%for entry in entries%}
    <li>
        <p>{{entry.date_added|date:'M d,Y H:i'}}</p><!--以M d, Y H:i这样的格式显示时间戳，接下来的一行显示text的完整值，而不仅仅是前50个字母-->
        <p>{{entry.text|linebreaks}}</p><!--竖线表示过滤器-->
        <p><a href="{%url 'learning_log:edit_entry' entry.id%}">Edit</a></p>
    </li>
    {%empty%}<!--使用此模板标签打印一条消息，告诉用户当前主题还没有条目-->
        <li>
            There are no entries for this topic yet.
        </li>
    {%endfor%}
</ul>
{% endblock content %}
</body>
</html>

learning_log/templates/learning_log/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主题页面</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    {% extends "learning_log/base.html" %}<!--第一行必须包含此标签，让Django知道它继承哪个夫模板-->
    {% block content %}
    <p>Topic Page</p>
    <ul>
        {% for topic in topics %}
            <li><a href="{% url 'learning_log:topic' topic.id%}">{{topic}}</a></li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'learning_log:new_topic'%}" id="a_new_topic" >Add</a>
    {% endblock content %}
</body>
</html>