learning_logs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('', include(('learning_log.urls', 'learning_log'), namespace="learning_log")),
    path('dailyLog/', include(('dailyLog.urls', 'dailyLog'), namespace='dailyLog')),
    path('titles/', include(('titles.urls', 'title'), namespace='title')),
    path('comments/', include(('comments.urls', 'comment'), namespace='comment')),
]

ll_env/Scripts/learning_logs/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

titles/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('show_titles/', index, name='titles'),
    path('post/<int:pk>/', detail, name='detail'),
    path('archives/<int:year>/<int:month>/', archive, name='archive'),
    path('categories/<int:pk>/', category, name='category'),
    path('tags/<int:pk>/', tag, name='tag'),
]

user/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import *

urlpatterns = [
    # path('showUser/', showUser_views),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),
]

titles/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models
from django.contrib import admin

# Create your models here.
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags


class Category(models.Model):
    name = models.CharField('分类名', max_length=100)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('标签', max_length=70)
    body = models.TextField('正文')
    # 创建时间
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 修改时间
    modified_time = models.DateTimeField()
    # blank=True允许空值
    # 文章摘要
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['create_time']

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        # 首先实例化一个 Markdown 类，用于渲染 body 的文本。
        # 由于摘要并不需要生成文章目录，所以去掉了目录拓展。
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        # 先将 Markdown 文本渲染成 HTML 文本
        # strip_tags 去掉 HTML 文本的全部 HTML 标签
        # 从文本摘取前 54 个字符赋给 excerpt
        self.excerpt = strip_tags(md.convert(self.body))[:20]
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('title:detail', kwargs={'pk': self.pk})


class PostAdmin(admin.ModelAdmin):
    '''PostAdmin继承自ModelAdmin，它有一个save_model 方法，这个方法只有一行代码：obj.save()
    的作用就是将此 Modeladmin 关联注册的 model 实例（这里 Modeladmin 关联注册的是 Post）保存
    到数据库。这个方法接收四个参数，其中前两个，一个是 request，即此次的 HTTP 请求对象，第二个
    是 obj，即此次创建的关联对象的实例，于是通过复写此方法，就可以将 request.user 关联到创建的
    Post 实例上，然后将 Post 数据再保存到数据库：
    '''
    list_display = ['title', 'create_time', 'modified_time', 'category', 'author']
    fields = ['title', 'body', 'excerpt', 'category', 'tags']

    def save_model(self, request, obj, form, change):
        obj.author = request.user
        super().save_model(request, obj, form, change)

titles/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from markdown.extensions.toc import TocExtension, slugify
from pure_pagination import PaginationMixin

from .models import *
import markdown, re


# Create your views here.
def index(request):
    post_list = Post.objects.all().order_by('-create_time')
    return render(request, 'titles/index.html', context={'post_list': post_list})


def tag(request, pk):
    # 记得在开始部分导入 Tag 类
    t = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=t).order_by('-create_time')
    return render(request, 'titles/index.html', context={'post_list': post_list})


def category(request, pk):
    # 记得在开始部分导入 Category 类
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-create_time')
    return render(request, 'titles/index.html', context={'post_list': post_list})


def archive(request, year, month):
    post_list = Post.objects.filter(create_time__year=year,
                                    create_time__month=month
                                    ).order_by('-create_time')
    return render(request, 'titles/index.html', context={'post_list': post_list})


def detail(request, pk):
    '''
    注意这里我们用到了从 django.shortcuts 模块导入的 get_object_or_404 方法，
    其作用就是当传入的 pk 对应的 Post 在数据库存在时，就返回对应的 post，如果不存在，
    就给用户返回一个 404 错误，表明用户请求的文章不存在。
    markdown.markdown() 方法把 post.body 中的 Markdown 文本解析成了 HTML 文本。
    同时我们还给该方法提供了一个 extensions 的额外参数。其中 markdown.extensions.toc 
    就是自动生成目录的拓展
    '''
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify),
    ])
    post.body = md.convert(post.body)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''
    return render(request, 'titles/detail.html', context={'post': post})


class IndexView(PaginationMixin,ListView):
    model = Post
    template_name = 'titles/index.html'
    context_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 5

titles/templates/titles/inclusions/_archives.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>归档</title>
</head>
<body>
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'title:archive' date.year date.month %}">
                {{ date.year }} 年 {{ date.month }} 月
            </a>
        </li>
        {% empty %}
        暂无归档！
        {% endfor %}
    </ul>
</div>
</body>
</html>

titles/templates/titles/inclusions/_categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="widget widget-category">
  <h3 class="widget-title">分类</h3>
  <ul>
    {% for category in category_list %}
      <li>
        <a href="{% url 'title:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
      </li>
    {% empty %}
      暂无分类！
    {% endfor %}
  </ul>
</div>
</body>
</html>

titles/templates/titles/inclusions/_recent_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="widget widget-recent-posts">
  <h3 class="widget-title">最新文章</h3>
  <ul>
    {% for post in recent_post_list %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% empty %}
      暂无文章！
    {% endfor %}
  </ul>
</div>
</body>
</html>

titles/templates/titles/inclusions/_tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签云</h3>
    <ul>
        {% for tag in tag_list %}
        <li>
          <a href="{% url 'title:tag' tag.pk %}">{{ tag.name }} <span class="post-count"> ({{ tag.num_posts }}) </a>
        </li>
        {% empty %}
        暂无标签！
        {% endfor %}
    </ul>
</div>
</body>
</html>