dailyLog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('show_diary/', showDiary_views, name='showDia'),
    path('newEdit_diary/', newEditDiary_views, name='newEditDia'),
    path('show_inspiration/', showInspiration_views, name='showIns'),
    path('newEdit_inspiration/', newEditInspiration_views, name='newEditIns')
]

learning_log/urls.py
# 当前的URL文件位于下面注释中的文件中
"""定义learning_logs的URL模式"""
# 导入函数url将URL映射到试图
from django.conf.urls import url
from django.urls import path
# 导入views模块，其中的句点是让python从当前文件夹中导入视图
from . import views

# 包含可在应用程序learning_logs中请求的网页
urlpatterns = [
    # 主页
    # 添加代码来包含模块learning_logs，namespace是为了让learning_log的URL中的其他URL区分开来
    # 函数接收3个实参，第一个是正则表达式，找开头和结尾之间没有任何东西的URL，
    # 第二个实参指定了要调用的视图函数
    # 第三个实参将这个URL模式的名称指定为index，依此让我们在代码的其他地方引用它
    path('', views.index, name='index'),
    # 显示所有的主题
    path('topics/', views.topics, name='topics'),
    path('topic/(<topic_id>)/', views.topic, name='topic'),  # 与包含在两个斜杠内的整数匹配，#将捕获的值存储到topic_id中
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/(<topic_id>)/', views.new_entry, name='new_entry'),
    path('edit_entry/(<entry_id>)/', views.edit_entry, name='edit_entry'),
]
app_name = 'learning_log'

learning_logs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('', include(('learning_log.urls', 'learning_log'), namespace="learning_log")),
    path('dailyLog/', include(('dailyLog.urls', 'dailyLog'), namespace='dailyLog')),
    path('titles/', include(('titles.urls', 'title'), namespace='title')),
    path('comments/', include(('comments.urls', 'comment'), namespace='comment')),
]

ll_env/Scripts/learning_logs/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

user/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import *

urlpatterns = [
    # path('showUser/', showUser_views),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),
]

dailyLog/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Diaries(models.Model):
    weather = models.CharField(max_length=8, verbose_name='天气')
    mood = models.CharField(max_length=8, verbose_name='心情')
    event = models.CharField(max_length=30, verbose_name='事件')
    process = models.TextField(verbose_name='过程')
    date_created = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='拥有者', default=1)

    class Meta:
        verbose_name = '日记'
        verbose_name_plural = verbose_name
        ordering = ['date_created']

    def __str__(self):
        return self.event


class Inspirations(models.Model):
    topic = models.CharField(max_length=30, verbose_name='主题')
    detail = models.TextField(verbose_name='细节')
    date_created = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='拥有者', default=1)

    class Meta:
        verbose_name = '灵感'
        verbose_name_plural = verbose_name
        ordering = ['date_created']

    def __str__(self):
        return self.topic

dailyLog/forms.py
from django import forms

from .models import *


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diaries
        fields = ('weather', 'mood', 'event', 'process')


class InspirationForm(forms.ModelForm):
    class Meta:
        model = Inspirations
        fields = ('topic', 'detail')

dailyLog/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import *
from .models import *


# Create your views here.
@login_required
def showDiary_views(request):
    diarys = Diaries.objects.filter(owner=request.user).order_by('-date_created')
    return render(request, 'dailyLog/Diarys.html', locals())


@login_required
def newEditDiary_views(request):
    # diary = Diary.objects.get(id=diary_id)
    # if diaries.owner!=request.user:
    #     raise Http404
    if request.method != 'POST':
        form = DiaryForm()
    else:
        form = DiaryForm(request.POST)
        if form.is_valid():
            new_diary = form.save(commit=False)
            new_diary.owner = request.user
            new_diary.save()
            return HttpResponseRedirect(reverse('dailyLog:showDia'))
    return render(request, 'dailyLog/newDiarys.html', locals())


@login_required
def showInspiration_views(request):
    ins = Inspirations.objects.filter(owner=request.user).order_by('-date_created')
    return render(request, 'dailyLog/Inspirations.html', locals())


@login_required
def newEditInspiration_views(request):
    # ins = Inspiration.objects.get(id=inspiration_id)
    if request.method != 'POST':
        form = InspirationForm()
    else:
        form = InspirationForm(request.POST)
        if form.is_valid():
            new_diary = form.save(commit=False)
            new_diary.owner = request.user
            new_diary.save()
            return HttpResponseRedirect(reverse('dailyLog:showIns'))
    return render(request, 'dailyLog/newInspirations.html', locals())

dailyLog/templates/dailyLog/Diarys.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_log/base.html' %}
{% block content %}
    <p><a href="{% url 'dailyLog:newEditDia' %}">Add your diary</a></p>
    <ul>
        {% for diary in diarys %}
            <li>
            <p>Date：{{ diary.date_created|date:'Y M d' }}</p>
            <p>Weather：{{ diary.weather }}</p>
            <p>Mood：{{ diary.mood }}</p>
            <p>Event：{{ diary.event }}</p>
            <p>Process：{{ diary.process }}</p>
            </li>
        {% empty %}
            <li>快来记录你的专属日记吧！</li>
        {% endfor %}
    </ul>
{% endblock content %}
</body>
</html>

dailyLog/templates/dailyLog/Inspirations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_log/base.html' %}
{% block content %}
    <p><a href="{% url 'dailyLog:newEditIns' %}">Add your inspiration</a></p>
    <ul>
        {% for insp in ins %}
            <li>
            <p>Date：{{ insp.date_created|date:'Y M d' }}</p>
            <p>Topic：{{ insp.topic }}</p>
            <p>Details：{{ insp.detail }}</p>
            </li>
        {% empty %}
            <li>记下你的灵感！</li>
        {% endfor %}
    </ul>
{% endblock content %}
</body>
</html>

dailyLog/templates/dailyLog/newDiarys.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_log/base.html" %}<!--第一行必须包含此标签，让Django知道它继承哪个夫模板-->
{% block content %}
    {#<p>#}
    {#    <a href="{%url 'learning_log:topic' topic.id%}">{{topic}}</a>#}
    {#</p>#}
    <form action="{% url 'dailyLog:newEditDia'  %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Add your diary</button>
    </form>
{% endblock content %}
</body>
</html>

dailyLog/templates/dailyLog/newInspirations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_log/base.html" %}<!--第一行必须包含此标签，让Django知道它继承哪个夫模板-->
{% block content %}
    {#<p>#}
    {#    <a href="{%url 'learning_log:topic' topic.id%}">{{topic}}</a>#}
    {#</p>#}
    <form action="{% url 'dailyLog:newEditIns' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Recording</button>
    </form>
{% endblock content %}
</body>
</html>